name: streamlit
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - python-dotenv
    - streamlit
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly==5.19.0
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    # - scikit-learn
    # - seaborn